# Generated by Django 3.2.15 on 2022-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetychecklistquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
