# Generated by Django 3.2.15 on 2022-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeraccount_operationsaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operationsaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
        migrations.DeleteModel(
            name='OperationsUser',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('OPERATIONS', 'Operations'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], max_length=25),
        ),
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
        migrations.DeleteModel(
            name='OperationsAccount',
        ),
    ]
