#!/usr/bin/env bash



set -e
# sed -i -e "s/\$NGINX_PORT/${PORT}/g" /etc/nginx/nginx.conf

# sed -i "s/\$NGINX_PORT/${PORT}/g" /etc/nginx/nginx.conf

# nginx -c "$PWD/nginx.conf" &
# sed -i "s/\$NGINX_PORT/${PORT}/g" /etc/nginx/nginx.conf > tmp; cat tmp > /etc/nginx/nginx.conf; rm tmp &



# Apply database migrations
echo "Creating Data"
python ./manage.py createdata &

# python manage.py migrate &
# python /app/manage.py collectstatic --noinput &
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app &
wait -n

#####################################################################################
# Options to DEBUG Django server
# Optional commands to replace abouve gunicorn command

# Option 1:
# run gunicorn with debug log level
# gunicorn server.wsgi --bind 0.0.0.0:8000 --workers 1 --threads 1 --log-level debug

# Option 2:
# run development server
# DEBUG=True ./manage.py runserver 0.0.0.0:8000